>P1;HBA$ELEMA       
 
 V--LSDKDKTNVKATWSKVGDHASDYVAEALERMFFSFPTTKTYFPHF-DLSH-----GS
 GQVKGHGKKVGEALTQAVGHLDDLPSALSALSDLHAHKLRVDPVNFKLLSHCLLVTLSSH
 QPTEFTPEVHASLDKFLSNVSTVLTSKYR------
*
>P1;HBA$PHOVI       
 
 V--LSPADKTNVKATWDKIGGHAGEYGGEALERTFTAFPTTKTYFPHF-DLSH-----GS
 AQVKAHGKKVADALTTAVAHMDDLPGALSALSDLHAHKLRVDPVNFKLLSHCLLVTLACH
 HPADFTPAVHASLDKFFSAVSTVLTSKYR------
*
>P1;HBA$PHYCA       
 
 V--LSPADKTNVKAAWAKVGNHAADFGAEALERMFMSFPSTKTYFSHF-DLGH-----NS
 TQVKGHGKKVADALTKAVGHLDTLPDALSDLSDLHAHKLRVDPVNFKLLSHCLLVTLAAH
 LPGDFTPSVHASLDKFLASVSTVLTSKYR------
*
>P1;HBA$PONPY       
 
 V--LSPADKTNVKTAWGKVGAHAGDYGAEALERMFLSFPTTKTYFPHF-DLSH-----GS
 AQVKDHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAH
 LPAEFTPAVHASLDKFLASVSTVLTSKYR------
*
>P1;HBBA$CAPHI      
 
 M--LTAEEKAAVTGFWGKV--KVDEVGAEALGRLLVVYPWTQRFFEHFGDLSSADAVMNN
 AKVKAHGKKVLDSFSNGMKHLDDLKGTFAQLSELHCDKLHVDPENFKLLGNVLVVVLARH
 HGSEFTPLLQAEFQKVVAGVANALAHRYH------
*
>P1;HBBL$XENLA      
 
 V-HLSADEKSAINAVWSKV--NIENDGHDALTRLLVVFPWTQRYFSSFGNLSNVAAISGN
 AKVRAHGKKVLSAVDESIHHLDDIKNFLSVLSTKHAEELHVDPENFKRLADVLVIVLAGK
 LGAAFTPQVQAAWEKFSAGLVAALSHGYF------
*
>P1;HBBZ$MOUSE      
 
 MVHFTAEEKAAITSIWDKV--DLEKVGGETLGRLLIVYPWTQRFFDKFGNLSSALAIMGN
 PRIRAHGKKVLTSLGLGVKNMDNLKETFAHLSELHCDKLHVDPENFKLLGNMLVIVLSTH
 FAKEFTPEVQAAWQKLVIGVANALSHKYH------
*
>P1;HBD$AOTTR       
 
 V-HLTGDEKSAVAALWGKV--NVEEVGGEALGRLLVVYPWTQRFFESFGALSSPDAVMGN
 PKVKAHGKKVLGAFSDGLAHLDNLKGTFAQLSELHCDKLHVDPENFRLLGNVLVCVLARN
 FGKEFTPLLQAAFQKVVAGVATALAHKYH------
*
>P1;MYG$CALJA       
 
 G--LSDGEWQLVLNVWGKVEADIPSHGQEVLISLFKGHPETLEKFDKFKHLKSEDEMKAS
 EELKKHGVTVLTALGGILKKKGHHEAELKPLAQSHATKHKIPVKYLEFISDAIVHVLQKK
 HPGDFGADAQGAMKKALELFRNDMAAKYKELGFQG
*
>P1;MYG$CANFA       
 
 G--LSDGEWQIVLNIWGKVETDLAGHGQEVLIRLFKNHPETLDKFDKFKHLKTEDEMKGS
 EDLKKHGNTVLTALGGILKKKGHHEAELKPLAQSHATKHKIPVKYLEFISDAIIQVLQSK
 HSGDFHADTEAAMKKALELFRNDIAAKYKELGFQG
*
>P1;MYG$CASFI       
 
 G--LSDGEWQLVLHVWGKVEADLAGHGQEVLIRLFKGHPETLEKFNKFKHIKSEDEMKAS
 EDLKKHGVTVLTALGGVLKKKGHHEAEIKPLAQSHATKHKIPIKYLEFISEAIIHVLQSK
 HPGXFGADAXGAMNKALELFRKDIAAKYKELGFQG
*
>P1;MYG$CEBAP       
 
 G--LSDGEWQLVLNVWGKVEADIPSHGQEVLISLFKGHPETLEKFDKFKHLKSEDEMKAS
 EELKKHGATVLTALGGILKKKGQHEAELKPLAQSHATKHKIPVKYLEFISDAIVHVLQKK
 HPGDFGADAQGAMKKALELFRNDMAAKYKELGFQG
*
